using System.Collections;
using System.Collections.Generic;
using NUnit.Framework;
using UnityEngine;
using UnityEngine.TestTools;
using UnityGLTF.KhrCharacter;
using Samples.Shared;

namespace KhrCharacterTestbed.Tests
{
    /// <summary>
    /// Runtime assertions for the animation pipeline shipped in commit 453d5e7
    /// (HumanoidClipFactory + AnimationClipCatalog + AnimationBinder + three demo scenes).
    ///
    /// SceneSmokeTests already covers "does the scene boot" for the three animation demos, but
    /// that suite would happily pass a runtime binding regression that leaves the character
    /// stationary (bind returns null, no Avatar assigned, Playables graph missing) as long as
    /// the scene finishes booting without a raised exception. This suite closes that gap: it
    /// asserts each of the pipeline's contract points against SC-Body (the canonical humanoid-
    /// capable synthetic fixture, generated by SampleCharacterFactory.GenerateSCBody).
    ///
    /// Anti-hollow: every assertion goes through the real plugin types (KhrCharacter,
    /// SkeletonMap) and the real pipeline entrypoints (AnimationBinder.Bind / Play), not mocks.
    /// A regression in KhrCharacter.SkeletonMap.BuildHumanoidAvatar would fail here.
    /// </summary>
    public class SandboxAnimationBinderTests
    {
        private readonly List<Object> _created = new List<Object>();

        [TearDown]
        public void TearDown()
        {
            foreach (var o in _created)
                if (o != null) Object.DestroyImmediate(o);
            _created.Clear();
        }

        // ── Humanoid mode: SC-Body has a full skeleton mapping, so Humanoid must build ─────────

        [UnityTest]
        public IEnumerator Bind_Humanoid_OnSCBody_SucceedsAndAssignsAvatar()
        {
            var load = SandboxTestUtil.LoadSynthetic("SC-Body.glb", _created);
            yield return load;
            var character = load.Current;

            Assert.IsTrue(AnimationBinder.IsSupported(character, RigMode.Humanoid),
                "SC-Body has a KHR skeleton_mapping; IsSupported(Humanoid) should return true.");

            var animator = AnimationBinder.Bind(character, RigMode.Humanoid);
            Assert.IsNotNull(animator, "AnimationBinder.Bind(Humanoid) returned null on SC-Body — " +
                             "SkeletonMap.SwitchRigMode(Humanoid) rejected the rig. If this fires, " +
                             "check SampleCharacterFactory.GenerateSCBody() bone naming.");
            Assert.IsNotNull(animator.avatar,
                "Humanoid Bind returned an Animator with no Avatar — BuildHumanoidAvatar's " +
                "output was null. The KHR plugin logs the rejection reason to the Console.");
            Assert.IsTrue(animator.avatar.isHuman,
                "Humanoid Bind produced an Avatar that isn't marked isHuman. Should never happen " +
                "given BuildHumanoidAvatar uses AvatarBuilder.BuildHumanAvatar.");
        }

        // ── Generic mode: works on any character, avatar deliberately null ──────────────────────

        [UnityTest]
        public IEnumerator Bind_Generic_ReturnsAnimatorWithNullAvatar()
        {
            var load = SandboxTestUtil.LoadSynthetic("SC-Body.glb", _created);
            yield return load;

            Assert.IsTrue(AnimationBinder.IsSupported(load.Current, RigMode.Generic),
                "Generic mode should be universally supported.");

            var animator = AnimationBinder.Bind(load.Current, RigMode.Generic);
            Assert.IsNotNull(animator, "Generic bind returned null. Bind should always add an Animator.");
            Assert.IsNull(animator.avatar,
                "Generic Bind must clear the avatar (clips target transform paths directly). " +
                "If this fires, AnimationBinder.BindGeneric is leaving a stale Avatar assigned.");
        }

        // ── IsSupported gates correctly for minimal characters without skeletons ────────────────

        [UnityTest]
        public IEnumerator IsSupported_Humanoid_False_OnCharacterWithoutSkeleton()
        {
            // SC-Face has only expressions — no skeleton mapping. Humanoid should be rejected.
            var load = SandboxTestUtil.LoadSynthetic("SC-Face.glb", _created);
            yield return load;
            Assert.IsFalse(AnimationBinder.IsSupported(load.Current, RigMode.Humanoid),
                "SC-Face has no skeleton mapping; IsSupported(Humanoid) must return false.");
        }

        // ── Play: creates the AnimationBinderPlayback component + a valid PlayableGraph ─────────

        [UnityTest]
        public IEnumerator Play_ProceduralClip_CreatesPlaybackComponent()
        {
            var load = SandboxTestUtil.LoadSynthetic("SC-Body.glb", _created);
            yield return load;
            var character = load.Current;

            var animator = AnimationBinder.Bind(character, RigMode.Humanoid)
                ?? AnimationBinder.Bind(character, RigMode.Generic);
            Assert.IsNotNull(animator, "Test precondition: at least one binding mode must succeed.");

            AnimationBinder.Play(animator, HumanoidClipFactory.IdleSway);

            var playback = animator.GetComponent<AnimationBinderPlayback>();
            Assert.IsNotNull(playback,
                "Play must attach an AnimationBinderPlayback component to own the PlayableGraph.");

            // Yield one frame so the Playables API has a chance to tick.
            yield return null;

            // Playing means the animator is in a valid update state. Non-hollow indicator that
            // the graph is live — a null / invalid graph would leave the animator idle.
            Assert.IsTrue(animator.isActiveAndEnabled,
                "Animator should be active + enabled after Play. If disabled, the graph teardown " +
                "path in AnimationBinderPlayback may have fired incorrectly.");
        }

        // ── Play idempotency: multiple Play calls swap the clip without stacking playbacks ──────

        [UnityTest]
        public IEnumerator Play_MultipleClips_ReusesSameComponent()
        {
            var load = SandboxTestUtil.LoadSynthetic("SC-Body.glb", _created);
            yield return load;
            var character = load.Current;

            var animator = AnimationBinder.Bind(character, RigMode.Humanoid)
                ?? AnimationBinder.Bind(character, RigMode.Generic);
            Assert.IsNotNull(animator);

            AnimationBinder.Play(animator, HumanoidClipFactory.IdleSway);
            AnimationBinder.Play(animator, HumanoidClipFactory.Wave);
            AnimationBinder.Play(animator, HumanoidClipFactory.Nod);
            yield return null;

            var playbacks = animator.GetComponents<AnimationBinderPlayback>();
            Assert.AreEqual(1, playbacks.Length,
                "Play must reuse the same AnimationBinderPlayback — [DisallowMultipleComponent] " +
                "protects against accidental double-add but the binder should also never try. " +
                $"Found {playbacks.Length} component(s).");
        }

        // ── Procedural clip paths align with SC-Body's bone naming ──────────────────────────────
        //
        // SC-Body's node names are PascalCase ("Hips", "Spine", "Head" — see
        // SampleCharacterFactory.Bone(vocab, nodeName, ...): nodeName is the GameObject name;
        // the lowercase vocab is the KHR skeleton_mapping key). HumanoidClipFactory writes
        // curves under BOTH conventions so the clips drive whichever the character uses.
        // This test catches the "clips play but nothing moves" silent regression that would
        // otherwise slip past SceneSmokeTests.

        [UnityTest]
        public IEnumerator ProceduralClipPaths_ResolveToSCBodyBones()
        {
            var load = SandboxTestUtil.LoadSynthetic("SC-Body.glb", _created);
            yield return load;
            var character = load.Current;

            var boneNames = new HashSet<string>();
            foreach (var t in character.GetComponentsInChildren<Transform>(true))
                boneNames.Add(t.name);

            Assert.IsTrue(boneNames.Contains("Hips"),
                "SC-Body must contain a 'Hips' Transform for IdleSway / WalkInPlace clips to " +
                "produce visible motion. If missing, SampleCharacterFactory.GenerateSCBody may " +
                "have been refactored — update HumanoidClipFactory paths to match.");
            Assert.IsTrue(boneNames.Contains("Spine"),
                "SC-Body must contain a 'Spine' Transform for IdleSway spine-roll to apply.");
            Assert.IsTrue(boneNames.Contains("Head"),
                "SC-Body must contain a 'Head' Transform for the Nod clip to apply.");
            Assert.IsTrue(
                boneNames.Contains("LeftUpperLeg") || boneNames.Contains("LeftLeg"),
                "SC-Body must contain a left-upper-leg bone under one of the common naming " +
                "conventions for the WalkInPlace clip to affect it.");
        }
    }
}
