using System.Collections;
using System.Collections.Generic;
using NUnit.Framework;
using UnityEngine;
using UnityEngine.TestTools;
using UnityGLTF.KhrCharacter;
using Samples.Shared;

namespace KhrCharacterTestbed.Tests
{
    /// <summary>
    /// Runtime assertions for the animation pipeline shipped in commit 453d5e7
    /// (HumanoidClipFactory + AnimationClipCatalog + AnimationBinder + three demo scenes).
    ///
    /// SceneSmokeTests already covers "does the scene boot" for the three animation demos, but
    /// that suite would happily pass a runtime binding regression that leaves the character
    /// stationary (bind returns null, no Avatar assigned, Playables graph missing) as long as
    /// the scene finishes booting without a raised exception. This suite closes that gap: it
    /// asserts each of the pipeline's contract points against SC-Body (the canonical humanoid-
    /// capable synthetic fixture, generated by SampleCharacterFactory.GenerateSCBody).
    ///
    /// Anti-hollow: every assertion goes through the real plugin types (KhrCharacter,
    /// SkeletonMap) and the real pipeline entrypoints (AnimationBinder.Bind / Play), not mocks.
    /// A regression in KhrCharacter.SkeletonMap.BuildHumanoidAvatar would fail here.
    /// </summary>
    public class SandboxAnimationBinderTests
    {
        private readonly List<Object> _created = new List<Object>();

        [TearDown]
        public void TearDown()
        {
            foreach (var o in _created)
                if (o != null) Object.DestroyImmediate(o);
            _created.Clear();
        }

        // ── Humanoid mode: SC-Body has a full skeleton mapping, so Humanoid must build ─────────

        [UnityTest]
        public IEnumerator Bind_Humanoid_OnSCBody_SucceedsAndAssignsAvatar()
        {
            var load = SandboxTestUtil.LoadSynthetic("SC-Body.glb", _created);
            yield return load;
            var character = load.Current;

            Assert.IsTrue(AnimationBinder.IsSupported(character, RigMode.Humanoid),
                "SC-Body has a KHR skeleton_mapping; IsSupported(Humanoid) should return true.");

            var animator = AnimationBinder.Bind(character, RigMode.Humanoid);
            Assert.IsNotNull(animator, "AnimationBinder.Bind(Humanoid) returned null on SC-Body — " +
                             "SkeletonMap.SwitchRigMode(Humanoid) rejected the rig. If this fires, " +
                             "check SampleCharacterFactory.GenerateSCBody() bone naming.");
            Assert.IsNotNull(animator.avatar,
                "Humanoid Bind returned an Animator with no Avatar — BuildHumanoidAvatar's " +
                "output was null. The KHR plugin logs the rejection reason to the Console.");
            Assert.IsTrue(animator.avatar.isHuman,
                "Humanoid Bind produced an Avatar that isn't marked isHuman. Should never happen " +
                "given BuildHumanoidAvatar uses AvatarBuilder.BuildHumanAvatar.");
        }

        // ── Generic mode: works on any character, avatar deliberately null ──────────────────────

        [UnityTest]
        public IEnumerator Bind_Generic_ReturnsAnimatorWithNullAvatar()
        {
            var load = SandboxTestUtil.LoadSynthetic("SC-Body.glb", _created);
            yield return load;

            Assert.IsTrue(AnimationBinder.IsSupported(load.Current, RigMode.Generic),
                "Generic mode should be universally supported.");

            var animator = AnimationBinder.Bind(load.Current, RigMode.Generic);
            Assert.IsNotNull(animator, "Generic bind returned null. Bind should always add an Animator.");
            Assert.IsNull(animator.avatar,
                "Generic Bind must clear the avatar (clips target transform paths directly). " +
                "If this fires, AnimationBinder.BindGeneric is leaving a stale Avatar assigned.");
        }

        // ── IsSupported gates correctly for minimal characters without skeletons ────────────────

        [UnityTest]
        public IEnumerator IsSupported_Humanoid_False_OnCharacterWithoutSkeleton()
        {
            // SC-Face has only expressions — no skeleton mapping. Humanoid should be rejected.
            var load = SandboxTestUtil.LoadSynthetic("SC-Face.glb", _created);
            yield return load;
            Assert.IsFalse(AnimationBinder.IsSupported(load.Current, RigMode.Humanoid),
                "SC-Face has no skeleton mapping; IsSupported(Humanoid) must return false.");
        }

        // ── Play: creates the AnimationBinderPlayback component + a valid PlayableGraph ─────────

        [UnityTest]
        public IEnumerator Play_ProceduralClip_CreatesPlaybackComponent()
        {
            var load = SandboxTestUtil.LoadSynthetic("SC-Body.glb", _created);
            yield return load;
            var character = load.Current;

            var animator = AnimationBinder.Bind(character, RigMode.Humanoid)
                ?? AnimationBinder.Bind(character, RigMode.Generic);
            Assert.IsNotNull(animator, "Test precondition: at least one binding mode must succeed.");

            AnimationBinder.Play(animator, HumanoidClipFactory.IdleSway);

            var playback = animator.GetComponent<AnimationBinderPlayback>();
            Assert.IsNotNull(playback,
                "Play must attach an AnimationBinderPlayback component to own the PlayableGraph.");

            // Yield one frame so the Playables API has a chance to tick.
            yield return null;

            // Playing means the animator is in a valid update state. Non-hollow indicator that
            // the graph is live — a null / invalid graph would leave the animator idle.
            Assert.IsTrue(animator.isActiveAndEnabled,
                "Animator should be active + enabled after Play. If disabled, the graph teardown " +
                "path in AnimationBinderPlayback may have fired incorrectly.");
        }

        // ── Play idempotency: multiple Play calls swap the clip without stacking playbacks ──────

        [UnityTest]
        public IEnumerator Play_MultipleClips_ReusesSameComponent()
        {
            var load = SandboxTestUtil.LoadSynthetic("SC-Body.glb", _created);
            yield return load;
            var character = load.Current;

            var animator = AnimationBinder.Bind(character, RigMode.Humanoid)
                ?? AnimationBinder.Bind(character, RigMode.Generic);
            Assert.IsNotNull(animator);

            AnimationBinder.Play(animator, HumanoidClipFactory.IdleSway);
            AnimationBinder.Play(animator, HumanoidClipFactory.Wave);
            AnimationBinder.Play(animator, HumanoidClipFactory.Nod);
            yield return null;

            var playbacks = animator.GetComponents<AnimationBinderPlayback>();
            Assert.AreEqual(1, playbacks.Length,
                "Play must reuse the same AnimationBinderPlayback — [DisallowMultipleComponent] " +
                "protects against accidental double-add but the binder should also never try. " +
                $"Found {playbacks.Length} component(s).");
        }

        // ── Procedural clip paths align with SC-Body's bone naming ──────────────────────────────
        //
        // SC-Body's node names are PascalCase ("Hips", "Spine", "Head" — see
        // SampleCharacterFactory.Bone(vocab, nodeName, ...): nodeName is the GameObject name;
        // the lowercase vocab is the KHR skeleton_mapping key). HumanoidClipFactory writes
        // curves under BOTH conventions so the clips drive whichever the character uses.
        // This test catches the "clips play but nothing moves" silent regression that would
        // otherwise slip past SceneSmokeTests.

        [UnityTest]
        public IEnumerator ProceduralClipPaths_ResolveToSCBodyBones()
        {
            var load = SandboxTestUtil.LoadSynthetic("SC-Body.glb", _created);
            yield return load;
            var character = load.Current;

            var boneNames = new HashSet<string>();
            foreach (var t in character.GetComponentsInChildren<Transform>(true))
                boneNames.Add(t.name);

            Assert.IsTrue(boneNames.Contains("Hips"),
                "SC-Body must contain a 'Hips' Transform for IdleSway / WalkInPlace clips to " +
                "produce visible motion. If missing, SampleCharacterFactory.GenerateSCBody may " +
                "have been refactored — update HumanoidClipFactory paths to match.");
            Assert.IsTrue(boneNames.Contains("Spine"),
                "SC-Body must contain a 'Spine' Transform for IdleSway spine-roll to apply.");
            Assert.IsTrue(boneNames.Contains("Head"),
                "SC-Body must contain a 'Head' Transform for the Nod clip to apply.");
            Assert.IsTrue(
                boneNames.Contains("LeftUpperLeg") || boneNames.Contains("LeftLeg"),
                "SC-Body must contain a left-upper-leg bone under one of the common naming " +
                "conventions for the WalkInPlace clip to affect it.");
        }

        // ── Character-adaptive clips resolve paths via KHR skeleton_mapping ─────────────────────
        //
        // Guards against a whole class of "clips play but nothing moves" regressions on rigs whose
        // bone names differ from the built-in fallback conventions (e.g. VRoid J_Bip_C_Head,
        // Mixamo mixamorig:Head). The test asserts the adaptive clip contains DIFFERENT paths
        // than the static clip does, proving the resolver actually rewired via SkeletonMap.

        [UnityTest]
        public IEnumerator BuildForCharacter_UsesSkeletonMapPaths()
        {
            var load = SandboxTestUtil.LoadSynthetic("SC-Body.glb", _created);
            yield return load;
            var character = load.Current;

            var adaptive = HumanoidClipFactory.BuildForCharacter("IdleSway", character);
            Assert.IsNotNull(adaptive, "BuildForCharacter must return a non-null clip on a KHR character.");
            Assert.IsTrue(adaptive.name.Contains("@"),
                "Character-adaptive clip name should include the character identifier (Name@Character convention).");

            // SC-Body's skeleton_mapping maps "hips" -> Transform("Hips"). ComputeRelativePath
            // from the character root gives "Hips" (root child). Verify the clip's curves target
            // that path by using SampleAnimation and observing effect on the "Hips" transform.
            var hips = FindDeep(character.transform, "Hips");
            Assert.IsNotNull(hips, "SC-Body precondition: Hips transform must exist.");

            float baselineY = hips.localPosition.y;
            adaptive.SampleAnimation(character, 1.0f); // quarter-cycle into a 4s sine
            float sampledY = hips.localPosition.y;

            Assert.Greater(Mathf.Abs(sampledY - baselineY), 0.0001f,
                $"Character-adaptive IdleSway should have driven Hips.localPosition.y from " +
                $"{baselineY} to {sampledY} — if unchanged, the clip's curve path didn't " +
                "resolve to the correct bone via SkeletonMap.TryGetBone.");

            yield return null;
        }

        [UnityTest]
        public IEnumerator BuildForCharacter_FallsBack_OnNonKhrCharacter()
        {
            // Fabricate a bare GameObject with no KhrCharacter component. BuildForCharacter must
            // fall back to the static clip rather than returning null or throwing.
            var bare = new GameObject("BareCharacter");
            _created.Add(bare);
            yield return null;

            var clip = HumanoidClipFactory.BuildForCharacter("IdleSway", bare);
            Assert.IsNotNull(clip, "BuildForCharacter must fall back to the static clip when " +
                             "the character has no SkeletonMap — got null instead.");
            Assert.AreEqual("IdleSway", clip.name,
                "Fallback should return the character-agnostic static clip (name = 'IdleSway', " +
                "no '@Character' suffix).");
        }

        // ── Rotation curves produce a small, valid rotation (not a quaternion-component flip) ────
        //
        // Regression net for the "totally warped" bug. HumanoidClipFactory previously authored
        // rotation as a single raw quaternion component (e.g. localRotation.x), leaving w=0 so Unity
        // snapped the bone to a ~180° flip. Rotations are now Euler-degree channels. This samples the
        // Nod clip at its +15° peak (t=0.5s) and asserts the head lands at ~Euler(15,0,0). The
        // path-resolution + scene-smoke suites can't catch this: they never inspect the resulting
        // rotation magnitude, so a flipped-but-moving bone would sail past them.
        [UnityTest]
        public IEnumerator RotationClip_ProducesSmallValidRotation_NotQuaternionFlip()
        {
            var load = SandboxTestUtil.LoadSynthetic("SC-Body.glb", _created);
            yield return load;
            var character = load.Current;

            var hub = character.GetComponent<KhrCharacter>();
            Assert.IsNotNull(hub, "SC-Body precondition: KhrCharacter hub must be present.");
            Assert.IsNotNull(hub.Skeleton, "SC-Body precondition: KhrCharacter must expose a SkeletonMap.");
            bool resolved = hub.Skeleton.TryGetBone("head", out var head);
            Assert.IsTrue(resolved && head != null,
                "SC-Body precondition: skeleton mapping must resolve the 'head' bone.");

            // Nod peaks at +15° about X at t=0.5s. SC-Body's bones have an IDENTITY bind rotation, so the
            // bind-relative result (bind * Euler(15,0,0)) equals the absolute Euler(15,0,0) here — which is what
            // we compare against. RotationClip_IsBindRelative_OnNonIdentityBindPose covers the non-identity
            // (VRoid) case where bind-relative and absolute diverge.
            var nod = HumanoidClipFactory.BuildForCharacter("Nod", character);
            Assert.IsNotNull(nod, "BuildForCharacter('Nod') returned null on a KHR character.");
            nod.SampleAnimation(character, 0.5f);

            float fromExpected = Quaternion.Angle(head.localRotation, Quaternion.Euler(15f, 0f, 0f));
            float fromIdentity = Quaternion.Angle(Quaternion.identity, head.localRotation);

            Assert.Less(fromExpected, 2f,
                $"Nod should place the head at ~Euler(15,0,0); it is {fromExpected:0.0}° away. A large " +
                "value means the euler curve didn't apply, or the axis/amplitude changed.");
            Assert.Less(fromIdentity, 45f,
                $"Head rotated {fromIdentity:0.0}° from identity — a >45° swing is the old " +
                "single-quaternion-component flip (w=0 → ~180°). Rotations must be Euler-degree channels.");
            Assert.Greater(fromIdentity, 3f,
                $"Head barely moved ({fromIdentity:0.0}°); the Nod curve didn't drive the head bone.");
            yield return null;
        }

        // ── Position curves stay anchored to the bind pose (no root displacement) ────────────────
        //
        // Regression net for the "root displacement" bug. HumanoidClipFactory's hips bob is authored
        // as a small delta around 0; played back as an ABSOLUTE clip it overwrote the hips' local
        // position, snapping SC-Body's Hips from y=1.0 to y≈0 and dropping the whole character. The
        // fix re-anchors position deltas on the bone's bind position. SC-Body's Hips bind y is 1.0
        // and IdleSway's hips delta is 0 at t=0 — so a correct clip leaves Hips at y≈1.0 there.
        [UnityTest]
        public IEnumerator PositionClip_IsBindRelative_NoRootDisplacement()
        {
            var load = SandboxTestUtil.LoadSynthetic("SC-Body.glb", _created);
            yield return load;
            var character = load.Current;

            var hub = character.GetComponent<KhrCharacter>();
            Assert.IsNotNull(hub, "SC-Body precondition: KhrCharacter hub must be present.");
            Assert.IsNotNull(hub.Skeleton, "SC-Body precondition: KhrCharacter must expose a SkeletonMap.");
            bool ok = hub.Skeleton.TryGetBone("hips", out var hips);
            Assert.IsTrue(ok && hips != null, "SC-Body precondition: skeleton mapping must resolve 'hips'.");

            float bindY = hips.localPosition.y;
            Assert.Greater(bindY, 0.1f,
                $"SC-Body's Hips should sit above the origin (expected ~1.0, got {bindY}). If this " +
                "fires, the fixture changed and this test can no longer detect root displacement.");

            var idle = HumanoidClipFactory.BuildForCharacter("IdleSway", character);
            Assert.IsNotNull(idle, "BuildForCharacter('IdleSway') returned null on a KHR character.");
            idle.SampleAnimation(character, 0f); // IdleSway's hips delta is 0 at t=0

            Assert.That(hips.localPosition.y, Is.EqualTo(bindY).Within(0.01f),
                $"At t=0 Hips should remain at its bind height {bindY:0.###}; got " +
                $"{hips.localPosition.y:0.###}. A value near 0 means the position curve is absolute " +
                "(overwrites the bind pose) — the character drops/displaces from the root.");
            yield return null;
        }

        // ── Rotation is bind-relative on a NON-identity bind pose (VRoid-collapse regression) ─────
        //
        // The character-adaptive clips bake bindRotation * Euler(delta) as quaternion curves. On a rig whose
        // bones have non-identity bind rotations (VRoid J_Bip_*), applying the delta ABSOLUTELY would
        // overwrite the bind pose and collapse the character. SC-Body's bind is identity, so we simulate a
        // non-identity bind by rotating the head before building the clip (BuildForCharacter snapshots the
        // current localRotation as the bind).
        [UnityTest]
        public IEnumerator RotationClip_IsBindRelative_OnNonIdentityBindPose()
        {
            var load = SandboxTestUtil.LoadSynthetic("SC-Body.glb", _created);
            yield return load;
            var character = load.Current;

            var hub = character.GetComponent<KhrCharacter>();
            Assert.IsNotNull(hub, "SC-Body precondition: KhrCharacter hub must be present.");
            Assert.IsNotNull(hub.Skeleton, "SC-Body precondition: KhrCharacter must expose a SkeletonMap.");
            bool resolved = hub.Skeleton.TryGetBone("head", out var head);
            Assert.IsTrue(resolved && head != null, "SC-Body precondition: 'head' bone must resolve.");

            var bind = Quaternion.Euler(0f, 40f, 20f); // stand-in for a VRoid non-identity bind rotation
            head.localRotation = bind;

            var nod = HumanoidClipFactory.BuildForCharacter("Nod", character);
            Assert.IsNotNull(nod, "BuildForCharacter('Nod') returned null on a KHR character.");
            nod.SampleAnimation(character, 0.5f); // Nod peaks at +15° about X at t=0.5s

            float fromBindRelative = Quaternion.Angle(head.localRotation, bind * Quaternion.Euler(15f, 0f, 0f));
            float fromAbsolute = Quaternion.Angle(head.localRotation, Quaternion.Euler(15f, 0f, 0f));

            Assert.Less(fromBindRelative, 2f,
                $"Nod should land the head at bind*Euler(15,0,0); it is {fromBindRelative:0.0}° away. A large " +
                "value means rotation is applied absolutely and would collapse a non-identity bind rig (VRoid).");
            Assert.Greater(fromAbsolute, 20f,
                $"Head is only {fromAbsolute:0.0}° from the ABSOLUTE Euler(15,0,0) — rotation isn't bind-relative " +
                "(the VRoid-collapse regression); expected it anchored on the ~44° bind instead.");
            yield return null;
        }

        private static Transform FindDeep(Transform parent, string name)
        {
            for (int i = 0; i < parent.childCount; i++)
            {
                var child = parent.GetChild(i);
                if (child.name == name) return child;
                var deep = FindDeep(child, name);
                if (deep != null) return deep;
            }
            return null;
        }
    }
}
